### ISSUE TITLE
avatar.bintools.gdb.parse_stream.ParseError: Unhandled Output: Python Exception <class 'ImportError'> No module named 'gdb':

### ISSUE THREAD

**Issue by ZakiG** [avatarone/gdb#1]
I noticed the hint:
```
== Notes == if you see errors like the following when running Avatar, the python support of GDB was not compiled well.
```
But I do have this problem, so how do I compile python support of GDB?
Since my python version is 3.4 , so I have tried the following configuration instructions so far:
```
./configure --with-python="/usr/bin/python3.4" --with-expat=yes --target=arm-none-eabi
make
```
But still report this error, how can I solve this problem.
Thanks

**Comment by ZakiG** [comment]
I think I have solved the above problems, but I have a new problem . 
When starting qemu, the following error occurred:
```
oss: Could not initialize DAC
oss: Failed to open `/dev/dsp'
oss: Reason: No such file or directory
oss: Could not initialize DAC
oss: Failed to open `/dev/dsp'
oss: Reason: No such file or directory
audio: Failed to create voice `lm4549.out'
```
How do I solve this problem.
Thanks

**Comment by mariusmue** [comment]
Hi @ZakiG.

Please note that avatarone has been superseeded by avatartwo (http://www.github.com/avatartwo), and hence no official support is given for this framework. The framework is mostly here for archiving reasons.

Anyhow, if I needed to guess: your first problem may be related to the fact that you use python 3.4 - according to the build description, this variation of gdb requires python 2.7.

Regarding your problems with Qemu, avatarone doesn't support plain qemu, but requires a modified version of s2e: https://github.com/avatarone/s2e

**Comment by ZakiG** [comment]
Thank you. I have solved this problem.
